### ISSUE TITLE
由4.2.2更新到4.3程序老是卡死，外拨电话的震动不起作用，望修复

### ISSUE THREAD

**Issue by liziqiang** [shaobin0604/CallVibrator#8]

**Comment by liziqiang** [comment]
机型：Galaxy Nexus
系统：Android4.3 stock

**Comment by shaobin0604** [comment]
@liziqiang 感谢反馈，得找个能升级到4.3的设备测试一下。

对了，你的设备 root 了没？

**Comment by liziqiang** [comment]
@shaobin0604 root了~

**Comment by iscottchina** [comment]
的确，Nexus 4升级4.3后接通震动无效。已Root。

**Comment by shaobin0604** [comment]
感谢反馈！

**Comment by shaobin0604** [comment]
找到原因了，4.3 gms radio log 的 TAG 从 `GSM` 改成 `GsmConnection`

**Comment by liziqiang** [comment]
@shaobin0604 太好了，期待尽快修复~

**Comment by shaobin0604** [comment]
@liziqiang @iscottchina 问题已修复，请问有没有邮箱？我把APK发过来帮忙测试一下。

**Comment by iscottchina** [comment]
@shaobin0604 iscottchina at gmail.com

**Comment by liziqiang** [comment]
ziqiang.lee@gmail.com
